FROM eclipse-temurin:18-jre-alpine
LABEL maintainer="starsers <yujieweb@foxmail.com>"

WORKDIR /opt/sym/
COPY target/symphony-bin/ /opt/sym/
COPY src/main/resources/docker/* /opt/sym/
RUN apk add --no-cache ca-certificates tzdata ttf-dejavu

ENV TZ=Asia/Shanghai
EXPOSE 8080

ENTRYPOINT [ "java", "-cp", "lib/*:.", "org.b3log.symphony.Server" ]
