FROM eclipse-temurin:18-jre-alpine
LABEL maintainer="starsers <yujieweb@foxmail.com>"

WORKDIR /opt/bluebook/
COPY target/symphony-bin/ /opt/bluebook/
COPY src/main/resources/docker/* /opt/bluebook/
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk add --no-cache ca-certificates tzdata ttf-dejavu font-noto-cjk

ENV TZ=Asia/Shanghai
EXPOSE 8080

ENTRYPOINT [ "java", "-cp", "lib/*:.", "org.b3log.symphony.Server" ]
